[rospy.client][INFO] 2020-02-08 17:56:03,413: init_node, name[/ros_test], pid[14360]
[xmlrpc][INFO] 2020-02-08 17:56:03,419: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2020-02-08 17:56:03,419: Started XML-RPC server [http://huai:42885/]
[rospy.impl.masterslave][INFO] 2020-02-08 17:56:03,420: _ready: http://huai:42885/
[rospy.init][INFO] 2020-02-08 17:56:03,420: ROS Slave URI: [http://huai:42885/]
[xmlrpc][INFO] 2020-02-08 17:56:03,423: xml rpc node: starting XML-RPC server
[rospy.registration][INFO] 2020-02-08 17:56:03,423: Registering with master node http://localhost:11311
[rospy.init][INFO] 2020-02-08 17:56:03,520: registered with master
[rospy.rosout][INFO] 2020-02-08 17:56:03,520: initializing /rosout core topic
[rospy.rosout][INFO] 2020-02-08 17:56:03,522: connected to core topic /rosout
[rospy.simtime][INFO] 2020-02-08 17:56:03,523: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rospy.internal][INFO] 2020-02-08 17:56:03,747: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][INFO] 2020-02-08 17:56:06,445: topic[/Lines2d] adding connection to [/tracking_node], count 0
[rospy.internal][INFO] 2020-02-08 17:56:18,698: topic[/camera/infra1/image_rect_raw] adding connection to [http://huai:41845/], count 0
[rospy.internal][WARNING] 2020-02-08 17:56:33,983: Unknown error initiating TCP/IP socket to huai:56725 (http://huai:41845/): Traceback (most recent call last):
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 558, in connect
    self.read_header()
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 653, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rosgraph/network.py", line 362, in read_ros_handshake_header
    d = sock.recv(buff_size)
error: [Errno 104] Connection reset by peer

[rospy.internal][INFO] 2020-02-08 17:56:33,983: topic[/camera/infra1/image_rect_raw] removing connection to http://huai:41845/
[rospy.core][INFO] 2020-02-08 17:56:36,350: signal_shutdown [signal-2]
[rospy.internal][INFO] 2020-02-08 17:56:36,352: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2020-02-08 17:56:36,352: topic[/Lines2d] removing connection to /tracking_node
[rospy.impl.masterslave][INFO] 2020-02-08 17:56:36,352: signal-2
[rospy.core][INFO] 2020-02-08 17:56:36,517: signal_shutdown [atexit]
[rospy.client][INFO] 2020-02-08 17:56:42,362: init_node, name[/ros_test], pid[14961]
[xmlrpc][INFO] 2020-02-08 17:56:42,367: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2020-02-08 17:56:42,367: Started XML-RPC server [http://huai:37033/]
[rospy.init][INFO] 2020-02-08 17:56:42,367: ROS Slave URI: [http://huai:37033/]
[rospy.impl.masterslave][INFO] 2020-02-08 17:56:42,368: _ready: http://huai:37033/
[rospy.registration][INFO] 2020-02-08 17:56:42,373: Registering with master node http://localhost:11311
[xmlrpc][INFO] 2020-02-08 17:56:42,374: xml rpc node: starting XML-RPC server
[rospy.init][INFO] 2020-02-08 17:56:42,468: registered with master
[rospy.rosout][INFO] 2020-02-08 17:56:42,468: initializing /rosout core topic
[rospy.rosout][INFO] 2020-02-08 17:56:42,470: connected to core topic /rosout
[rospy.simtime][INFO] 2020-02-08 17:56:42,471: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rospy.internal][INFO] 2020-02-08 17:56:42,707: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][INFO] 2020-02-08 17:56:45,110: topic[/Lines2d] adding connection to [/tracking_node], count 0
[rospy.internal][INFO] 2020-02-08 17:56:46,140: topic[/camera/infra1/image_rect_raw] adding connection to [http://huai:45029/], count 0
[rospy.internal][WARNING] 2020-02-08 18:00:59,658: Unknown error initiating TCP/IP socket to huai:44409 (http://huai:45029/): Traceback (most recent call last):
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 558, in connect
    self.read_header()
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 653, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rosgraph/network.py", line 362, in read_ros_handshake_header
    d = sock.recv(buff_size)
error: [Errno 104] Connection reset by peer

[rospy.internal][INFO] 2020-02-08 18:00:59,658: topic[/camera/infra1/image_rect_raw] removing connection to http://huai:45029/
[rospy.core][INFO] 2020-02-08 18:01:01,508: signal_shutdown [signal-2]
[rospy.internal][INFO] 2020-02-08 18:01:01,510: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2020-02-08 18:01:01,510: topic[/Lines2d] removing connection to /tracking_node
[rospy.impl.masterslave][INFO] 2020-02-08 18:01:01,510: signal-2
[rospy.core][INFO] 2020-02-08 18:01:01,675: signal_shutdown [atexit]
